feat(/calendar,/originstory,/events,/about): Implement UI
delta/aaveg-app pull request #6
Opened 2022-06-08 17:17 UTC by avvsrohith

In this Pull Request.

- Implemented design and UI for /originStory, /about, /calendar, /events.
- Added required assets.
- Implemented modular structure by including widgets of same page in a folder

2022-06-09 05:23 UTC, Ram-20062003 commented on lib/pages/events_page.dart
> +        appBar: AppBar(
We are not having an app bar in the app. so remove this.
And see how the navicon was implemented in authpage

2022-06-09 05:25 UTC, Ram-20062003 commented on lib/pages/originstory_page.dart
> +      appBar: AppBar(
Same here

2022-06-09 05:32 UTC, Ram-20062003 commented on lib/utils/constants.dart
> +class ClientCredentials {
Creditionals should be in config. dart.Pls, clear this.

2022-06-09 05:32 UTC, Ram-20062003 commented on lib/pages/calendar_page.dart
> +      appBar: AppBar(
Same remove app bar

2022-06-09 05:33 UTC, Ram-20062003 commented on lib/pages/about_page.dart
> +      appBar: AppBar(
Here also again

2022-06-09 21:56 UTC, SuhailAhmed2627 commented
Pull Rebase

2022-06-10 09:28 UTC, Ram-20062003 requested changes

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/pages/about_page.dart
> +          decoration: BoxDecoration(
Background image takes some margin here ig .Add fit parameter here as Boxfit.fill

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/pages/about_page.dart
> +              image: DecorationImage(
Add black overlay also.

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/views/widgets/Events/event_card.dart
> +                                fontSize: totalHeight * 0.024,
make font bigger this is too small for smaller screen mobiles.

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/views/widgets/Events/event_card.dart
> +                            'click here for rulebook -->',
Insert the poper straight line arrow as in figma. not dotted lines

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/views/widgets/Events/event_card.dart
> +                                '      ' +
To the left of the dates there should be a calendar icon . it is not there.Check figma once

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/views/widgets/Events/event_card.dart
> +                                  style: TextStyle(
it should be italics and should have arrow after it

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/views/widgets/Events/event_card.dart
> +                                      fontSize: totalHeight * 0.012),
The font size here really makes the know more hidden.maintain a constant visible font-size

2022-06-10 09:28 UTC, Ram-20062003 commented on lib/views/widgets/About/about_text.dart
> +    return Container(
it is better to put a singlechildscrollview .because of lots of text will be coming later

2022-06-10 09:31 UTC, Ram-20062003 commented
![Screenshot from 2022-06-10 14-56-03](https://user-images.githubusercontent.com/83528327/173035958-476519df-b067-48e7-b536-be4a4dd90c77.png)

**the text in calendar is really difficult to read** .Do look into it

2022-06-14 21:49 UTC, Ram-20062003 approved these changes

2022-06-14 21:49 UTC, merged